events {
    # This block handles connection processing. 
    # 1024 is a standard default for max simultaneous connections per worker.
    worker_connections 1024;
}

http {
    # Include standard MIME types so NGINX knows how to serve CSS, JS, etc.
    include /etc/nginx/mime.types;

    server {
        # 1. The Socket Bind
        listen 443 ssl;
        
        # 2. The Identity
        server_name snazzal.42.fr;

        # 3. The Security Badges (From Phase 2)
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;
        
        # 4. The Subject Constraint
        ssl_protocols TLSv1.2 TLSv1.3;

        # 5. The Filesystem Map
        root /var/www/wordpress;
        index index.php index.html;

        # 6. The Intercom (FastCGI Handoff)
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}